# launch config
dataroot: '/raid/carta'
logdir: '/raid/carta/ex_model_cl/logs/_final_results/mt_cifar10'
assess_runs: 5
no_ray: false
debug: false

# hardware config
max_cpus: 30
cpus_per_job: 3
cuda: true
max_gpus: 5
gpus_per_job: 1

# scenario
experiment_type: train_ed
scenario: mt_cifar10
model: resnet

### hyper-params
strategy: dimpression_ed

buffer_size: 5000
num_iter_per_exp: 50000
train_mb_size: 128
lr: 0.1

loss_type: mse
reset_model: false

init_from_expert: false
bias_normalization: false

buffer_blur: 0.01
buffer_bns: 0.0
buffer_iter: 500
buffer_lr: 0.1
buffer_mb_size: 1024
buffer_wd: 0.0001
ce_loss: true


grid:
  buffer_temperature:
    - 2.0
    - 20.0
  buffer_beta:
    - 0.1
    - 1.0
    - 10.0